public class Main {
    public static void main(String[] args) throws Exception {
        Collection coll1 = new MyCollectionImpl();
        Collection coll = new MyCollectionImpl(new String[]{"qweqwe","123123123","fffgdfgd"} );
        System.out.println("________________");
        coll.add("33333");
        System.out.println("__________________");
        coll1.add("33333");
        coll1.add("33333");
        coll1.add("33333");
        coll1.add("33333");
        coll1.add("33333");
        coll1.add("33333");
        System.out.println("__________________");
        coll.add(4,"444444");
        coll.add(2,"222222");
        coll.add(2,"22222");
        coll.add(2,"2222");
        coll.add(2,"222");
        coll.add(2,"22");
        coll.add("5");
        coll.add("55");
        coll.add("555");
        coll.add("5555");
        coll.add("66");
        coll.add("66");
        coll.add("66");
        coll.add("66");
        coll.add("777");
        System.out.println("__________________");
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
        coll.delete(0);
//        coll.delete(0);
        coll.add("7");
        coll.add("7");
        coll.add("8");
        coll.add("9");
//        coll.add("7");
//        coll.add("7");
//        coll.add("7");
        System.out.println(coll.get(0));
        System.out.println(coll.get(1));
        System.out.println(coll.get(2));
        System.out.println(coll.get(3));
        System.out.println(coll.contain("71")+" contains");
        coll1.clear();
        coll.clear();
        System.out.println("size ="+coll1.size());
        coll1.add("qwer");
        coll.add("qwer");
        System.out.println("size ="+coll1.size());
        System.out.println(coll.equals(coll1));
    }
}
